# Generated by Django 4.2.16 on 2025-11-17 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AntoniaApp', '0002_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
